// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Pool50.SQLite;

namespace pool.Migrations
{
    [DbContext(typeof(PoolContext))]
    [Migration("20180626130300_InitialCreate")]
    partial class InitialCreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.1-rtm-30846");

            modelBuilder.Entity("Pool50.SQLite.Owner", b =>
                {
                    b.Property<int>("OwnerId")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("FullName");

                    b.Property<int>("TeamId");

                    b.Property<string>("Username");

                    b.HasKey("OwnerId");

                    b.HasIndex("TeamId");

                    b.ToTable("Owners");
                });

            modelBuilder.Entity("Pool50.SQLite.Team", b =>
                {
                    b.Property<int>("TeamId")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Name");

                    b.HasKey("TeamId");

                    b.ToTable("Teams");

                    b.HasData(
                        new { TeamId = 1, Name = "Arizona Cardinals" },
                        new { TeamId = 2, Name = "Atlanta Falcons" },
                        new { TeamId = 3, Name = "Baltimore Ravens" },
                        new { TeamId = 4, Name = "Buffalo Bills" },
                        new { TeamId = 5, Name = "Carolina Panthers" },
                        new { TeamId = 6, Name = "Chicago Bears" },
                        new { TeamId = 7, Name = "Cincinnati Bengals" },
                        new { TeamId = 8, Name = "Cleveland Browns" },
                        new { TeamId = 9, Name = "Dallas Cowboys" },
                        new { TeamId = 10, Name = "Denver Broncos" },
                        new { TeamId = 11, Name = "Detroit Lions" },
                        new { TeamId = 12, Name = "Green Bay Packers" },
                        new { TeamId = 13, Name = "Houston Texans" },
                        new { TeamId = 14, Name = "Indianapolis Colts" },
                        new { TeamId = 15, Name = "Jacksonville Jaguars" },
                        new { TeamId = 16, Name = "Kansas City Chiefs" },
                        new { TeamId = 17, Name = "Miami Dolphins" },
                        new { TeamId = 18, Name = "Minnesota Vikings" },
                        new { TeamId = 19, Name = "New England Patriots" },
                        new { TeamId = 20, Name = "New Orleans Saints" },
                        new { TeamId = 21, Name = "New York Giants" },
                        new { TeamId = 22, Name = "New York Jets" },
                        new { TeamId = 23, Name = "Oakland Raiders" },
                        new { TeamId = 24, Name = "Philadelphia Eagles" },
                        new { TeamId = 25, Name = "Pittsburgh Steelers" },
                        new { TeamId = 26, Name = "St. Louis Rams" },
                        new { TeamId = 27, Name = "San Diego Chargers" },
                        new { TeamId = 28, Name = "San Francisco 49ers" },
                        new { TeamId = 29, Name = "Seattle Seahawks" },
                        new { TeamId = 30, Name = "Tampa Bay Buccaneers" },
                        new { TeamId = 31, Name = "Tennessee Titans" },
                        new { TeamId = 32, Name = "Washington Redskins" }
                    );
                });

            modelBuilder.Entity("Pool50.SQLite.Owner", b =>
                {
                    b.HasOne("Pool50.SQLite.Team", "Team")
                        .WithMany()
                        .HasForeignKey("TeamId")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
